/*
Query12:Find the total revenue generated by each employee.
Query Description:In this query, i have  join the "orders" table with the "employees" table using
 the "employee_id" column. The SUM() function calculates the sum of the "orders.freight" column.
 By grouping the results by the "employee_id", we can get the total revenue generated by each employee.
*/

SELECT employees.employee_id, SUM(Orders.freight) AS TotalRevenue
FROM orders
JOIN employees ON orders.employee_id = employees.employee_id
GROUP BY employees.employee_id;
